### ISSUE TITLE
Idea: Put docker images on dockerhub

### ISSUE THREAD

**Issue by Weilkiti** [gorenje/sysmlv2-jupyter-docker#1]
First, thanks for creating the Docker container for Binder.

I would have one more wish :-)
If the Docker images are also deployed on dockerhub, they can be easily used by all servers running Docker and not only by Binder.

Good idea?

Cheers,
Tim

**Comment by gorenje** [comment]
Hi Tim, 

First off, thank you for the inspiration - MBSE4U.com made me do it :)

It's definitely a good idea and I haven't yet done it since I was more focused on running this locally (although even
then having an image on dockerhub would help!)

I'll get this setup later today and update here.

What would also be extremely useful would be a way of sharing (thinking here of editing and updating) existing notebooks, kind of similar to a wiki or some such. The only way I have so far found was by using JupyterHub. Another alternative is forking and merging but that's a lot of overhead, especially for people not familar with GitHub.

Any ideas? 

Cheers,
Gerrit

**Comment by gorenje** [comment]
Ok, it's up on docker hub --> https://hub.docker.com/r/gorenje/sysmlv2-jupyter

**Comment by Weilkiti** [comment]
Hi Gerrit,

Thanks for the dockerhub 😊 However, I tried it and it doesn’t work. I have not been able to figure out what the problem is. I use the service https://sloppy.io and get these messages in the console. This repeats endlessly:

2021-03-11 18:30:23 > | Welcome to JShell -- Version 17-ea
2021-03-11 18:30:23 > | For an introduction type: /help intro
2021-03-11 18:30:23 > Mar 11, 2021 5:30:20 PM java.util.prefs.FileSystemPreferences$1 run
2021-03-11 18:30:23 > INFO: Created user preferences directory.
2021-03-11 18:30:34 > Starting task jr-sysmlv2lab_jupyter_sysmlv2lab.7723534c-828f-11eb-bc4b-0a35b8c6a8a8
2021-03-11 18:30:34 > | Welcome to JShell -- Version 17-ea
2021-03-11 18:30:34 > | For an introduction type: /help intro
2021-03-11 18:30:34 > Mar 11, 2021 5:30:31 PM java.util.prefs.FileSystemPreferences$1 run
2021-03-11 18:30:34 > INFO: Created user preferences directory.

Your idea of sharing existing notebooks with edit functionality is exactly what I am looking for 😊 People can play around with SysML v2, share ideas, etc. I would like to provide such a service with sloppy.io.

Kind regards,
Tim

**Comment by gorenje** [comment]
Ok, added specfic Dockerfiles for Dockerhub and rebuilt the images - can you have a try?

The problem was the missing entrypoint in the Dockefile. Mybinder doesn't like one and so the default dockerfiles doesn't have one.

**Comment by Weilkiti** [comment]
Great! Thanks! It seems to work. I could not finally test it, because I have an issue with sloppy and have to ask a colleague to help me.

I will send a link as soon as it finally runs.

**Comment by gorenje** [comment]
DM'ed with OP and am closing this.
